apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "43"
    field.cattle.io/creatorId: user-nz878
  creationTimestamp: "2019-03-07T09:42:14Z"
  generation: 46
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-zen-stg-batch-python-luigi
  name: batch-python-luigi
  namespace: zen-stg
  resourceVersion: "88544917"
  selfLink: /apis/apps/v1beta2/namespaces/zen-stg/deployments/batch-python-luigi
  uid: 49c078da-40bd-11e9-b65e-000c29b6fbe9
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-zen-stg-batch-python-luigi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-08-11T02:56:37Z"
        workload.cattle.io/state: '{"emp0ZXM1MjE=":"c-jsvxz:m-3f76fdb3ac7b"}'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-zen-stg-batch-python-luigi
    spec:
      containers:
      - env:
        - name: TZ
          value: Asia/Tokyo
        image: ken-toitsu-registry.ad.zenjukyo.gr.jp:80/zen/batch-python-luigi:v1.0.0
        imagePullPolicy: Always
        name: batch-python-luigi
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /opt/services/report/src/etc/default.ini
          name: cm-batch-python-lujgi-defaultini
          subPath: default.ini
      dnsPolicy: ClusterFirst
      nodeName: zjtes521
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 438
          name: batch-python-luigi-defaultini
          optional: true
        name: cm-batch-python-lujgi-defaultini
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-03-30T01:16:23Z"
    lastUpdateTime: "2020-03-30T01:16:23Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-03-07T09:42:14Z"
    lastUpdateTime: "2020-08-11T02:56:39Z"
    message: ReplicaSet "batch-python-luigi-745c97bd7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 46
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
