apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  annotations:
    field.cattle.io/creatorId: user-nz878
  creationTimestamp: "2019-03-07T09:10:35Z"
  generation: 8
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: statefulSet-zen-stg-db-redis
  name: db-redis
  namespace: zen-stg
  resourceVersion: "87176643"
  selfLink: /apis/apps/v1beta2/namespaces/zen-stg/statefulsets/db-redis
  uid: de06ad06-40b8-11e9-b9e9-000c293d92a0
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: statefulSet-zen-stg-db-redis
  serviceName: db-redis
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-08-03T05:13:48Z"
        field.cattle.io/ports: '[[{"containerPort":6379,"dnsName":"db-redis","kind":"ClusterIP","name":"6379tcp02","protocol":"TCP","sourcePort":0}]]'
        workload.cattle.io/state: '{"emp0ZXM2MjE=":"c-jsvxz:m-7147ae20d16d"}'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: statefulSet-zen-stg-db-redis
    spec:
      containers:
      - args:
        - redis-server
        - --appendonly
        - "yes"
        env:
        - name: TZ
          value: Asia/Tokyo
        image: ken-toitsu-registry.ad.zenjukyo.gr.jp:80/zen/db-redis:v1.0.0
        imagePullPolicy: Always
        name: db-redis
        ports:
        - containerPort: 6379
          name: 6379tcp02
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      nodeName: zjtes621
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: RollingUpdate
status:
  collisionCount: 0
  currentReplicas: 1
  currentRevision: db-redis-ddf94c6b6
  observedGeneration: 8
  readyReplicas: 1
  replicas: 1
  updateRevision: db-redis-ddf94c6b6
  updatedReplicas: 1
