apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  annotations:
    field.cattle.io/creatorId: user-nz878
  creationTimestamp: "2019-08-01T10:14:01Z"
  generation: 10
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: statefulSet-zen-stg-storage-mariadb-batch
  name: storage-mariadb-batch
  namespace: zen-stg
  resourceVersion: "87176762"
  selfLink: /apis/apps/v1beta2/namespaces/zen-stg/statefulsets/storage-mariadb-batch
  uid: 1595c1a9-b445-11e9-845d-000c293d92a0
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: statefulSet-zen-stg-storage-mariadb-batch
  serviceName: db-mariadb
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-08-03T05:14:11Z"
        field.cattle.io/ports: '[[{"containerPort":3306,"dnsName":"storage-mariadb-batch","kind":"ClusterIP","name":"3306tcp02","protocol":"TCP","sourcePort":0}]]'
        workload.cattle.io/state: '{"emp0ZXM0MjE=":"c-jsvxz:m-95ed34a52585","emp0ZXM2MjE=":"c-jsvxz:m-7147ae20d16d"}'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: statefulSet-zen-stg-storage-mariadb-batch
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: zen_report
        - name: MYSQL_USER
          value: zen
        - name: TZ
          value: Asia/Tokyo
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: secret-storage-mariadb-batch
              optional: false
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: secret-storage-mariadb-batch
              optional: false
        image: ken-toitsu-registry.ad.zenjukyo.gr.jp:80/zen/storage-mariadb-batch:v1.0.0
        imagePullPolicy: Always
        name: storage-mariadb-batch
        ports:
        - containerPort: 3306
          name: 3306tcp02
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /var/log/mysql
          name: vol-storage-mariadb-batch-logs
        - mountPath: /var/lib/mysql
          name: vol-storage-mariadb-batch-data
        - mountPath: /etc/mysql/conf.d/mariadb.cnf
          name: cm-storage-mariadb-batch-mycnf
          subPath: mariadb.cnf
        - mountPath: /opt/services/data-migration/files
          name: vol-storage-mariadb-batch-files
      dnsPolicy: ClusterFirst
      nodeName: zjtes421
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 755
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/log/storage-mariadb-batch
          type: DirectoryOrCreate
        name: vol-storage-mariadb-batch-logs
      - hostPath:
          path: /export/storage-mariadb-batch/data
          type: ""
        name: vol-storage-mariadb-batch-data
      - configMap:
          defaultMode: 420
          name: storage-mariadb-batch-mariadbcnf
          optional: false
        name: cm-storage-mariadb-batch-mycnf
      - hostPath:
          path: /export/storage-mariadb-batch/files
          type: DirectoryOrCreate
        name: vol-storage-mariadb-batch-files
  updateStrategy:
    type: RollingUpdate
status:
  collisionCount: 0
  currentReplicas: 1
  currentRevision: storage-mariadb-batch-7c6979ddc6
  observedGeneration: 10
  readyReplicas: 1
  replicas: 1
  updateRevision: storage-mariadb-batch-7c6979ddc6
  updatedReplicas: 1
