apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    field.cattle.io/creatorId: user-nz878
    field.cattle.io/publicEndpoints: '[{"addresses":["172.16.253.155"],"port":80,"protocol":"HTTP","serviceName":"zen-stg:ingress-298c72c6fec587ff5117b1d2f50052f7","ingressName":"zen-stg:lb-storage-zenko","hostname":"ken-toitsu-zenko.ad.zenjukyo.gr.jp","allNodes":true}]'
  creationTimestamp: "2019-03-07T09:26:09Z"
  generation: 11
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-zen-stg-storage-zenko
  name: storage-zenko
  namespace: zen-stg
  resourceVersion: "87176979"
  selfLink: /apis/apps/v1beta2/namespaces/zen-stg/deployments/storage-zenko
  uid: 0b01fb47-40bb-11e9-b9e9-000c293d92a0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-zen-stg-storage-zenko
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-08-03T05:16:10Z"
        field.cattle.io/ports: '[[{"containerPort":8000,"dnsName":"storage-zenko","kind":"ClusterIP","name":"8000tcp02","protocol":"TCP","sourcePort":0}]]'
        workload.cattle.io/state: '{"emp0ZXM0MjE=":"c-jsvxz:m-95ed34a52585"}'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-zen-stg-storage-zenko
    spec:
      containers:
      - env:
        - name: REMOTE_MANAGEMENT_DISABLE
          value: "1"
        - name: TZ
          value: Asia/Tokyo
        image: ken-toitsu-registry.ad.zenjukyo.gr.jp:80/zen/storage-zenko:v1.0.0
        imagePullPolicy: Always
        name: storage-zenko
        ports:
        - containerPort: 8000
          name: 8000tcp02
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /usr/src/app/localData
          name: vol-storage-zenko-data-localdata
        - mountPath: /usr/src/app/localMetadata
          name: vol-storage-zenko-data-localmetadata
        - mountPath: /usr/src/app/config.json
          name: cm-storage-zenko-configjson
          subPath: config.json
      dnsPolicy: ClusterFirst
      nodeName: zjtes421
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /export/storage-zenko/data/localdata
          type: DirectoryOrCreate
        name: vol-storage-zenko-data-localdata
      - hostPath:
          path: /export/storage-zenko/data/localmetadata
          type: DirectoryOrCreate
        name: vol-storage-zenko-data-localmetadata
      - configMap:
          defaultMode: 420
          items:
          - key: config.json
            path: config.json
          name: storage-zenko-configjson
          optional: true
        name: cm-storage-zenko-configjson
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-03-30T01:15:42Z"
    lastUpdateTime: "2020-03-30T01:15:42Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-03-07T09:26:10Z"
    lastUpdateTime: "2020-08-03T05:16:13Z"
    message: ReplicaSet "storage-zenko-675b8d5747" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 11
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
