apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "193"
    field.cattle.io/creatorId: user-nz878
  creationTimestamp: "2019-03-07T09:12:50Z"
  generation: 221
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-zen-stg-web-django
  name: web-django
  namespace: zen-stg
  resourceVersion: "92347906"
  selfLink: /apis/apps/v1beta2/namespaces/zen-stg/deployments/web-django
  uid: 2ea5d26e-40b9-11e9-b9e9-000c293d92a0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-zen-stg-web-django
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-08-31T10:09:52Z"
        field.cattle.io/ports: '[[{"containerPort":80,"dnsName":"web-django","kind":"ClusterIP","name":"80tcp02","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-zen-stg-web-django
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - web
      containers:
      - args:
        - gunicorn
        - --workers=17
        - --threads=1
        - --timeout=1200
        - --chdir=webapp
        - --bind=:80
        - exs_main.wsgi:application
        env:
        - name: DJANGO_DEBUG
          value: "1"
        - name: TZ
          value: Asia/Tokyo
        image: ken-toitsu-registry.ad.zenjukyo.gr.jp:80/zen/web-django:v1.0.1
        imagePullPolicy: Always
        name: web-django
        ports:
        - containerPort: 80
          name: 80tcp02
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /opt/services/djangoapp/src/etc/default.ini
          name: cm-web-django-defaultini
          subPath: default.ini
        - mountPath: /opt/services/djangoapp/src/logs
          name: vol-web-django-logs
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 755
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 256
          name: web-django-defaultini
          optional: false
        name: cm-web-django-defaultini
      - hostPath:
          path: /var/log/web-django
          type: DirectoryOrCreate
        name: vol-web-django-logs
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-03-07T09:12:50Z"
    lastUpdateTime: "2020-08-31T10:10:47Z"
    message: ReplicaSet "web-django-7dcc889cb8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-09-02T01:14:25Z"
    lastUpdateTime: "2020-09-02T01:14:25Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 221
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
